# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=96, unique=True)),
                ('category', models.CharField(blank=True, max_length=96, unique=True)),
                ('description', models.CharField(blank=True, max_length=96, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=96, unique=True)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SharedItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('trade_type', models.CharField(blank=True, max_length=96, unique=True)),
                ('trade_status', models.CharField(blank=True, max_length=96, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharingapi.Item')),
                ('location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharingapi.Location')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=96, unique=True)),
                ('firstname', models.CharField(blank=True, max_length=96, unique=True)),
                ('surname', models.CharField(blank=True, max_length=96, unique=True)),
                ('email', models.CharField(blank=True, max_length=96, unique=True)),
                ('phone', models.IntegerField(blank=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=96, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='shareditem',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharingapi.User'),
        ),
    ]
